### ISSUE TITLE
License

### ISSUE THREAD

**Issue by radarsat1** [uBLAS/numeric_bindings#2]
Hi, I assume this is based off the old project at https://mathema.tician.de/dl/software/boost-numeric-bindings/ but I just noticed that you don't include the license file.  Is it possible to add it?

**Comment by radarsat1** [comment]
Ah, apologies, I've just noticed that the license is mentioned at the top of every file, so I guess there is no problem.  I will note that though that the text says,

    See accompanying file LICENSE_1_0.txt

which isn't there ;)

**Comment by terborg** [comment]
Added the Boost license file.

**Comment by radarsat1** [comment]
Thanks! :)
